POST http://localhost:3000/signup
Content-Type: application/json

{
  "fullname": "Jond",
  "email": "khhaanalnischal2075@sSommmmMmMthing.com",
  "password": "samD45678"
}

POST http://localhost:3000/signin
Content-Type: application/json

{
  "email": "khhaanalnischal2075@sSommmmMmMthing.com",
  "password": "samD45678"
}


