import sanitizeHtml from "sanitize-html";

export function sanitizeMDXContent(content: string): string {
  return sanitizeHtml(content, {
    allowedTags: [
      "p",
      "div",
      "span",
      "strong",
      "em",
      "u",
      "s",
      "ul",
      "ol",
      "li",
      "label",
      "input",
      "img",
      "a",
      "blockquote",
      "code",
      "pre",
      "h1",
      "h2",
      "h3",
      "h4",
      "h5",
      "h6",
      "br",
      "table",
      "thead",
      "tbody",
      "tr",
      "th",
      "td",
      "hr",
      "iframe",
    ],
    allowedAttributes: {
      "*": ["class", "style", "data-type", "data-checked"],
      a: ["href", "target", "rel"],
      img: ["src", "alt", "width", "height"],
      iframe: ["src", "width", "height", "frameborder", "allow", "allowfullscreen", "loading", "title"],
      input: ["type", "checked", "disabled"],
      th: ["colspan", "rowspan"],
      td: ["colspan", "rowspan"],
    },
    selfClosing: ["img", "input", "br", "hr"],
    disallowedTagsMode: "discard",
  });
}
