import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { DialogProvider } from "@/components/ui/dialog";
import { Navbar } from "@/components/layout/navbar";
import { Footer } from "@/components/layout/footer";
import { SiteJsonLd } from "@/components/seo/site-json-ld";
import { getSiteOrigin } from "@/lib/site-url";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
});



export async function generateMetadata({
  params,
}: {
  params: Promise<{ locale: string }>;
}): Promise<Metadata> {
  const { locale } = await params;
  const isNp = locale === "np";
  const origin = getSiteOrigin();
  return {
    title: {
      template: "%s | Laganiforum",
      default: isNp ? "लगानीफोरम | वित्तीय ज्ञान" : "Laganiforum | Finance & Trading",
    },
    description: isNp
      ? "लगानीफोरम - नेप्से, फरेक्स र व्यक्तिगत वित्त सम्बन्धी शैक्षिक विश्लेषण।"
      : "Laganiforum - NEPSE, forex, and personal finance education in English and Nepali.",
    metadataBase: new URL(origin),
    openGraph: {
      siteName: "Laganiforum",
      locale: isNp ? "ne_NP" : "en_US",
      type: "website",
    },
    twitter: {
      card: "summary_large_image",
    },
    // NOTE: Do NOT set alternates here. This layout wraps every locale page, so
    // setting static language links here would override the correct per-page
    // hreflang generated by buildPageMetadata() / localeAlternates().
    // Each page's own generateMetadata() sets the correct alternates.
  };
}

export default async function LocaleLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;
  const isNp = locale === "np";

  return (
    <div
      lang={isNp ? "ne" : locale}
      className={`${geistSans.variable} ${geistMono.variable} min-h-dvh flex flex-col ${isNp ? "np-locale font-mukta" : "font-sans"}`}
    >
      <SiteJsonLd locale={locale} />
      <DialogProvider>
        <Navbar locale={locale} />
        <main className="flex-1">{children}</main>
        <Footer locale={locale} />
      </DialogProvider>
    </div>
  );
}
